### ISSUE TITLE
uve_compiler branch setup does not work

### ISSUE THREAD

**Issue by haeunlee99** [hpc-ulisboa/UVE#1]
Hello, 

I have been trying to execute following commands as documented in the README.md of uve_compiler branch. 

> git submodule update --init --recursive
> ./set_repos.sh
> ./inject_uve.sh
> ./configure.sh

However, I get such an error while executing the first command. 

> root@e45b589594d3:/home/UVE# git submodule update --init --recursive
> Cloning into '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu'...
> fatal: unable to connect to github.com:
> github.com[0: 52.78.231.108]: errno=Connection timed out
> 
> fatal: clone of 'git://github.com/riscv/riscv-qemu.git' into submodule path '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu' failed
> Failed to clone 'riscv-qemu'. Retry scheduled
> Cloning into '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu'...
> fatal: unable to connect to github.com:
> github.com[0: 15.164.81.167]: errno=Connection timed out
> 
> fatal: clone of 'git://github.com/riscv/riscv-qemu.git' into submodule path '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu' failed
> Failed to clone 'riscv-qemu' a second time, aborting
> Failed to recurse into submodule path 'ext_modules/riscv-gnu-toolchain'

I am running the commands at ubuntu 20.04 with gem5 dependencies installed. 

Also, I cannot find rebuild.sh file. Is it replaced with rebuild_gas.sh?

Thank you in advance!

**Comment by jsonlee0x02** [comment]
Where is the llvm compiler for UVE?
As presented in the paper, "Compiling for Vector Extensions with Stream-based Specialization", the toolchain for UVE is implemented based on LLVM

**Comment by AnaBSF** [comment]
> Hello,
> 
> I have been trying to execute following commands as documented in the README.md of uve_compiler branch.
> 
> > git submodule update --init --recursive
> > ./set_repos.sh
> > ./inject_uve.sh
> > ./configure.sh
> 
> However, I get such an error while executing the first command.
> 
> > root@e45b589594d3:/home/UVE# git submodule update --init --recursive
> > Cloning into '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu'...
> > fatal: unable to connect to github.com:
> > github.com[0: 52.78.231.108]: errno=Connection timed out
> > fatal: clone of 'git://github.com/riscv/riscv-qemu.git' into submodule path '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu' failed
> > Failed to clone 'riscv-qemu'. Retry scheduled
> > Cloning into '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu'...
> > fatal: unable to connect to github.com:
> > github.com[0: 15.164.81.167]: errno=Connection timed out
> > fatal: clone of 'git://github.com/riscv/riscv-qemu.git' into submodule path '/home/UVE/ext_modules/riscv-gnu-toolchain/riscv-qemu' failed
> > Failed to clone 'riscv-qemu' a second time, aborting
> > Failed to recurse into submodule path 'ext_modules/riscv-gnu-toolchain'
> 
> I am running the commands at ubuntu 20.04 with gem5 dependencies installed.

Unfortunately, the qemu repository has been moved and its reference has not been updated. However, that error is not fatal on my end. 

> Also, I cannot find rebuild.sh file. Is it replaced with rebuild_gas.sh?

The README.md file has been updated and this mistake has been fixed.

**Comment by AnaBSF** [comment]
> Where is the llvm compiler for UVE? As presented in the paper, "Compiling for Vector Extensions with Stream-based Specialization", the toolchain for UVE is implemented based on LLVM

The LLVM-based toolchain will be made publicly available soon.
